import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TransformaSans = localFont({
  // Định nghĩa tên biến CSS
  variable: "--font-transforma-sans",
  display: "swap",
  src: [
    // File Regular (thường là độ đậm 400)
    {
      path: "./../public/fonts/TransformaSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    // File Medium (thường là độ đậm 500)
    {
      path: "./../public/fonts/TransformaSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    // File Bold (thường là độ đậm 700)
    {
      path: "./../public/fonts/TransformaSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    // File Black (thường là độ đậm 900)
    {
      path: "./../public/fonts/TransformaSans-Black.ttf",
      weight: "900",
      style: "normal",
    },
    // ... Thêm tất cả các file khác của bạn (Light, ExtraBold, v.v.)
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${manrope.variable} `}>{children}</body>
    </html>
  );
}
